---
title: TESTSITE
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: This is a description.
baseurl: 
url: http://yourdomain.com
markdown: kramdown
breadcrumbs:
  root:
    hide: false
    image: false
